# Generated by Django 5.2.8 on 2025-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_product_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
